# Generated by Django 3.2.22 on 2023-10-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workregister',
            name='allocated_emp',
            field=models.ManyToManyField(related_name='works_allocated', to='Registration_Login.EmployeeRegister_Details'),
        ),
        migrations.AlterField(
            model_name='clientregister',
            name='client_bussiness_file',
            field=models.ImageField(default='', upload_to='client\\files'),
        ),
        migrations.AlterField(
            model_name='clienttask_register',
            name='task_file',
            field=models.FileField(default='', upload_to='work\\task\\files'),
        ),
        migrations.AlterField(
            model_name='workregister',
            name='work_file',
            field=models.FileField(default='', upload_to='work\\files'),
        ),
        migrations.CreateModel(
            name='WorkAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_discription', models.TextField(blank=True, default='', null=True)),
                ('wa_file', models.FileField(default='', upload_to='work\\files')),
                ('work_assign_progress', models.IntegerField(default=0)),
                ('work_assign_date', models.DateField(auto_now=True, null=True)),
                ('wa_from_date', models.DateField(null=True)),
                ('wa_due_date', models.DateField(null=True)),
                ('wa_status', models.IntegerField(default=0)),
                ('wa_type', models.IntegerField(default=0)),
                ('allocated_exemp', models.ManyToManyField(related_name='co_works_allocated', to='Registration_Login.EmployeeRegister_Details')),
                ('wa_clientId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.clientregister')),
                ('wa_compId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
                ('wa_tasksId', models.ManyToManyField(related_name='task_allocated', to='DM_Head.ClientTask_Register')),
                ('wa_work_allocate', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_tl', to='Registration_Login.employeeregister_details')),
                ('wa_work_regId', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.workregister')),
            ],
        ),
    ]
