# Generated by Django 4.2.3 on 2023-10-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('Mobile_no', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('passout_year', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('expereince', models.CharField(max_length=15)),
                ('previous_designation', models.CharField(max_length=255, null=True)),
                ('previous_company', models.CharField(max_length=255, null=True)),
                ('reason_for_registration', models.CharField(max_length=300)),
                ('status', models.CharField(default='not responded', max_length=100)),
                ('response', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
