# Generated by Django 4.2.3 on 2023-10-31 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DM_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='hr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.logregister_details'),
        ),
    ]
