# Generated by Django 4.2.3 on 2023-11-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_hr', '0002_candidatedetails_hr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='data_added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='reason',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
