# Generated by Django 4.2.3 on 2023-11-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_hr', '0006_alter_candidatedetails_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='Mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
