# Generated by Django 3.2.22 on 2023-10-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_lname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_email', models.EmailField(default='email@gmail.com', max_length=255)),
                ('company_image', models.FileField(default='', upload_to='profiles')),
                ('company_website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company_location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_active_status', models.IntegerField(default=0)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRegister_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dept_active_status', models.IntegerField(default=0)),
                ('dept_content', models.TextField(blank=True, default='', null=True)),
                ('dept_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('brd_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='DesignationRegister_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.IntegerField(default=0)),
                ('desig_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('desig_content', models.TextField(blank=True, default='', null=True)),
                ('desig_active_status', models.IntegerField(default=0)),
                ('desig_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('dept_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.departmentregister_details')),
                ('desig_brd_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='LogRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_username', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('log_date', models.DateField(auto_now_add=True, null=True)),
                ('log_time', models.TimeField(auto_now_add=True, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_staff', models.IntegerField(default=0)),
                ('active_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_regId', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_email', models.EmailField(default='email@gmail.com', max_length=255)),
                ('emp_profile', models.ImageField(default='', upload_to='profiles')),
                ('emp_file', models.FileField(default='', upload_to='employee_files')),
                ('emp_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('emp_location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('emp_district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('emp_state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('emp_active_status', models.IntegerField(default=0)),
                ('emp_verify_status', models.IntegerField(default=0)),
                ('emp_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_comp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
                ('emp_department_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.departmentregister_details')),
                ('emp_designation_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.designationregister_details')),
                ('logreg_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.logregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_email', models.EmailField(default='email@gmail.com', max_length=255)),
                ('dis_agencies', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_profife', models.FileField(default='', upload_to='profiles')),
                ('dis_file', models.FileField(default='', upload_to='employee_files')),
                ('dis_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dis_location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('dis_district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('dis_state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('dis_active_status', models.IntegerField(default=0)),
                ('dis_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('logdis_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.logregister_details')),
            ],
        ),
        migrations.AddField(
            model_name='businessregister_details',
            name='distributor_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.distributorregister_details'),
        ),
        migrations.AddField(
            model_name='businessregister_details',
            name='log_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.logregister_details'),
        ),
    ]
